"""
Read-only cross-reference: every player currently rostered to a live
Premier League club, checked against a Fantrax export (snapshot from
09/07/2026) for a club mismatch.

Why this exists: scripts/check_stale_player_clubs.py only catches a stale
club once a player has a scraped raw_stats appearance for their new club
this season -- it can't say anything about someone who transferred but
hasn't played a scraped match yet under EITHER club. Fantrax tracks the
whole player pool regardless of playing time, so it catches those too.

Matching rule, and why: Fantrax spells some names without accents and
occasionally uses a different first-name form (a nickname, e.g. "Louie"
vs "Lewis"), so name text can't always be compared literally. Matching
is done in two confidence tiers:
  - EXACT (accent-insensitive, case-insensitive) name match -- high
    confidence, safe to act on directly once you glance at the numbers.
  - FUZZY (closest normalized-name match, similarity >= 0.82) -- lower
    confidence. This tier produced false positives during testing on a
    common surname ("Ben Johnson" vs. two unrelated "Brennan Johnson" /
    "Henry Johnson" entries) -- always eyeball a fuzzy match before
    trusting it, it is a candidate, not a verdict.

This does NOT change any name spelling anywhere -- only ever reports a
club mismatch. WhoScored's spelling of a player's name is this app's
source of truth; Fantrax's spelling (accents dropped, etc.) is only used
to find the matching player, never to overwrite anything.

Players whose players.club is already outside this season's 20 live
clubs (Burnley, West Ham, Wolves -- last season's relegated three) are
skipped entirely; they're correctly not part of this season regardless
of what Fantrax does or doesn't say. Players with no Fantrax match at
all are also reported separately but are usually not a real problem --
Fantrax only tracks players relevant to fantasy scoring, so a fringe
academy/reserve player legitimately may not appear there; that's not
evidence their club is wrong.

Run: python3 cross_reference_fantrax_clubs.py
"""
import difflib
import sqlite3
import unicodedata

from init_db import DB_PATH

# Fantrax export snapshot: (player_name, club, position). Club codes
# already resolved to this app's full club names (ARS->Arsenal, etc.).
FANTRAX_ROWS = [
    ('Bruno Fernandes', 'Manchester United', 'M'),
    ('Cody Gakpo', 'Liverpool', 'M,F'),
    ('Vitaly Janelt', 'Brentford', 'M'),
    ('Lewis Hall', 'Newcastle', 'D'),
    ('Nobel Mendy', 'Hull', 'D'),
    ('Rayan Cherki', 'Manchester City', 'M'),
    ('James Tarkowski', 'Everton', 'D'),
    ('John Egan', 'Hull', 'D'),
    ('Cole Palmer', 'Chelsea', 'M,F'),
    ('Keane Lewis-Potter', 'Brentford', 'D,M,F'),
    ('Josko Gvardiol', 'Manchester City', 'D'),
    ('Morgan Rogers', 'Chelsea', 'M,F'),
    ('Joao Pedro', 'Chelsea', 'M,F'),
    ('Dominik Szoboszlai', 'Liverpool', 'D,M'),
    ('Erling Haaland', 'Manchester City', 'F'),
    ('Alexander Isak', 'Liverpool', 'F'),
    ('Tarik Muharemovic', 'Leeds', 'D'),
    ('Marcus Tavernier', 'Bournemouth', 'M'),
    ('Semi Ajayi', 'Hull', 'D'),
    ('Konstantinos Tzolakis', 'Hull', 'G'),
    ('Anton Stach', 'Leeds', 'M'),
    ('Bukayo Saka', 'Arsenal', 'M,F'),
    ('Joshua King', 'Fulham', 'M'),
    ('Mohamed Belloumi', 'Hull', 'M,F'),
    ('Tyrick Mitchell', 'Crystal Palace', 'D,M'),
    ('Bryan Mbeumo', 'Manchester United', 'M,F'),
    ('Jarrad Branthwaite', 'Everton', 'D'),
    ('Anan Khalaili', 'Crystal Palace', 'D,M,F'),
    ('Ben White', 'Arsenal', 'D'),
    ('Kiernan Dewsbury-Hall', 'Everton', 'M'),
    ('Maxim De Cuyper', 'Brighton', 'D,M'),
    ('Lukas Hornicek', 'Newcastle', 'G'),
    ('Luka Vuskovic', 'Brighton', 'D'),
    ('Martin Odegaard', 'Arsenal', 'M'),
    ('Alex Scott', 'Bournemouth', 'M'),
    ('Marc Guehi', 'Manchester City', 'D'),
    ('Riccardo Calafiori', 'Arsenal', 'D'),
    ('Ryan Giles', 'Hull', 'D'),
    ('Amar Dedic', 'Newcastle', 'D'),
    ('James Trafford', 'Leeds', 'G'),
    ('Luke Shaw', 'Manchester United', 'D'),
    ('Murillo', 'Nottingham Forest', 'D'),
    ('Ethan Ampadu', 'Leeds', 'D,M'),
    ('Jorrel Hato', 'Chelsea', 'D,M'),
    ('Abdul Fatawu', 'Ipswich', 'M,F'),
    ('Morgan Gibbs-White', 'Nottingham Forest', 'M,F'),
    ('Neco Williams', 'Nottingham Forest', 'D,M'),
    ('Granit Xhaka', 'Sunderland', 'M'),
    ('Anthony Elanga', 'Newcastle', 'M,F'),
    ('Diego Gomez', 'Brighton', 'M,F'),
    ('Michael Kayode', 'Brentford', 'D'),
    ('Julio Enciso', 'Ipswich', 'M'),
    ('Maxence Lacroix', 'Chelsea', 'D'),
    ('Iliman Ndiaye', 'Manchester City', 'M,F'),
    ('Nordi Mukiele', 'Sunderland', 'D'),
    ('Antoine Semenyo', 'Manchester City', 'M,F'),
    ('Reinildo', 'Sunderland', 'D'),
    ('Kai Havertz', 'Arsenal', 'F'),
    ('Jeremy Jacquet', 'Liverpool', 'D'),
    ('Sven Botman', 'Newcastle', 'D'),
    ('Olivier Boscagli', 'Brighton', 'D'),
    ('Mamadou Sangare', 'Brentford', 'M'),
    ('Chris Richards', 'Crystal Palace', 'D'),
    ('Phil Foden', 'Manchester City', 'M'),
    ('James Justin', 'Leeds', 'D,M'),
    ('Vitalii Mykolenko', 'Everton', 'D'),
    ('Declan Rice', 'Arsenal', 'M'),
    ('Gabriel Magalhaes', 'Arsenal', 'D'),
    ('Pascal Gross', 'Brighton', 'M'),
    ('Nikola Milenkovic', 'Nottingham Forest', 'D'),
    ('Yoane Wissa', 'Newcastle', 'F'),
    ('Jan-Paul van Hecke', 'Tottenham', 'D'),
    ('Kevin Schade', 'Brentford', 'M,F'),
    ('Jordan Pickford', 'Everton', 'G'),
    ('Tyrique George', 'Everton', 'M,F'),
    ('Kristoffer Ajer', 'Brentford', 'D'),
    ('Danny Ballard', 'Sunderland', 'D'),
    ('Leif Davis', 'Ipswich', 'D'),
    ('Elliot Anderson', 'Manchester City', 'M'),
    ('David Raya', 'Arsenal', 'G'),
    ('Daichi Kamada', 'Crystal Palace', 'M,F'),
    ('Virgil van Dijk', 'Liverpool', 'D'),
    ('Alisson Becker', 'Liverpool', 'G'),
    ('Kjell Scherpen', 'Ipswich', 'G'),
    ('Jair Cunha', 'Nottingham Forest', 'D'),
    ('Enzo Le Fee', 'Sunderland', 'M,F'),
    ('Milos Kerkez', 'Liverpool', 'D'),
    ('Issa Diop', 'Ipswich', 'D'),
    ('Evanilson', 'Bournemouth', 'F'),
    ('Malick Thiaw', 'Newcastle', 'D'),
    ('Adam Wharton', 'Crystal Palace', 'M'),
    ('Timothy Castagne', 'Fulham', 'D,M'),
    ('Bobby Thomas', 'Coventry', 'D'),
    ('Pedro Neto', 'Chelsea', 'M,F'),
    ('Emiliano Martinez', 'Chelsea', 'G'),
    ('Caoimhin Kelleher', 'Brentford', 'G'),
    ('Abdukodir Khusanov', 'Manchester City', 'D'),
    ('Adrien Truffert', 'Bournemouth', 'D'),
    ('Harrison Armstrong', 'Everton', 'M'),
    ('Sasa Lukic', 'Ipswich', 'M'),
    ('Jayden Bogle', 'Leeds', 'D,M'),
    ('Gonzalo Garcia', 'Fulham', 'F'),
    ('Dean Henderson', 'Crystal Palace', 'G'),
    ('Kobbie Mainoo', 'Manchester United', 'M'),
    ('Regan Slater', 'Hull', 'M'),
    ('Harvey Barnes', 'Newcastle', 'M,F'),
    ('Antonio Silva', 'Bournemouth', 'D'),
    ('Romeo Lavia', 'Chelsea', 'M'),
    ('Thomas Meunier', 'Sunderland', 'D'),
    ('Victor Munoz', 'Liverpool', 'M,F'),
    ('Florian Wirtz', 'Liverpool', 'M'),
    ('Jaydee Canvot', 'Crystal Palace', 'D'),
    ('Jack Hinshelwood', 'Brighton', 'M'),
    ('James Hill', 'Bournemouth', 'D'),
    ('Malick Yalcouye', 'Brighton', 'M'),
    ('Alex Iwobi', 'Fulham', 'M,F'),
    ('Ruben Dias', 'Manchester City', 'D'),
    ('Nilson Angulo', 'Sunderland', 'M,F'),
    ('James Mcatee', 'Nottingham Forest', 'M'),
    ('Thierno Barry', 'Everton', 'F'),
    ('Jay da Silva', 'Coventry', 'D'),
    ('Djordje Petrovic', 'Bournemouth', 'G'),
    ('Dara O\'Shea', 'Ipswich', 'D'),
    ('Mats Wieffer', 'Brighton', 'D,M'),
    ('Ian Maatsen', 'Aston Villa', 'D'),
    ('Christos Tzolis', 'Arsenal', 'M,F'),
    ('Noah Sadiki', 'Sunderland', 'M'),
    ('Rodrigo Bentancur', 'Tottenham', 'M'),
    ('Matt Grimes', 'Coventry', 'M'),
    ('Cesar Palacios', 'Fulham', 'M'),
    ('Gianluigi Donnarumma', 'Manchester City', 'G'),
    ('Youri Tielemans', 'Manchester United', 'M'),
    ('Ola Aina', 'Nottingham Forest', 'D,M'),
    ('Antonin Kinsky', 'Tottenham', 'G'),
    ('Milan van Ewijk', 'Coventry', 'D'),
    ('Antonee Robinson', 'Fulham', 'D'),
    ('Lewis Dunk', 'Brighton', 'D'),
    ('Emersonn', 'Ipswich', 'F'),
    ('Boubacar Kamara', 'Aston Villa', 'M'),
    ('Joe Willock', 'Newcastle', 'M'),
    ('Jaka Bijol', 'Leeds', 'D'),
    ('Sandro Tonali', 'Tottenham', 'M'),
    ('Xaver Schlager', 'Nottingham Forest', 'M'),
    ('Matty Cash', 'Aston Villa', 'D'),
    ('Harry Maguire', 'Manchester United', 'D'),
    ('Senne Lammens', 'Manchester United', 'G'),
    ('Eddie Nketiah', 'Crystal Palace', 'F'),
    ('Dan Ndoye', 'Nottingham Forest', 'M,F'),
    ('Trai Hume', 'Sunderland', 'D,M'),
    ('Zion Suzuki', 'Aston Villa', 'G'),
    ('Oscar Bobb', 'Fulham', 'M'),
    ('Nathan Collins', 'Brentford', 'D'),
    ('Ao Tanaka', 'Leeds', 'M'),
    ('Pedro Porro', 'Tottenham', 'D'),
    ('Andrew Robertson', 'Tottenham', 'D'),
    ('Ross Barkley', 'Aston Villa', 'M'),
    ('Marcus Rashford', 'Manchester United', 'M,F'),
    ('Cristhian Mosquera', 'Arsenal', 'D'),
    ('Lewie Coyle', 'Hull', 'D'),
    ('Alexis Mac Allister', 'Liverpool', 'M'),
    ('Matz Sels', 'Nottingham Forest', 'G'),
    ('Ronald Araujo', 'Liverpool', 'D'),
    ('Wesley Fofana', 'Chelsea', 'D'),
    ('Aurele Amenda', 'Coventry', 'D'),
    ('Hayden Hackney', 'Everton', 'M'),
    ('Axel Disasi', 'Crystal Palace', 'D'),
    ('Igor Thiago', 'Brentford', 'F'),
    ('Matheus Cunha', 'Manchester United', 'M,F'),
    ('Mikkel Damsgaard', 'Brentford', 'M'),
    ('Mathys Tel', 'Tottenham', 'M,F'),
    ('Justin Kluivert', 'Bournemouth', 'M,F'),
    ('Daizen Maeda', 'Ipswich', 'M,F'),
    ('Lewis Miley', 'Newcastle', 'D,M'),
    ('Yeremy Pino', 'Crystal Palace', 'M,F'),
    ('Diogo Dalot', 'Manchester United', 'D,M'),
    ('Micky van de Ven', 'Tottenham', 'D'),
    ('Dominic Calvert-Lewin', 'Leeds', 'F'),
    ('Marcelino Nunez', 'Ipswich', 'M'),
    ('Reece James', 'Chelsea', 'D,M'),
    ('George Hemmings', 'Aston Villa', 'M'),
    ('Dango Ouattara', 'Brentford', 'M,F'),
    ('Nico Elvedi', 'Leeds', 'D'),
    ('Joe Rodon', 'Leeds', 'D'),
    ('Josh Acheampong', 'Chelsea', 'D'),
    ('Calvin Bassey', 'Fulham', 'D'),
    ('Adam Smith', 'Bournemouth', 'D'),
    ('Jack Rudoni', 'Coventry', 'M'),
    ('Merlin Rohl', 'Everton', 'D,M'),
    ('Oliver McBurnie', 'Hull', 'F'),
    ('Bernd Leno', 'Fulham', 'G'),
    ('Ryan Gravenberch', 'Liverpool', 'M'),
    ('Exequiel Palacios', 'Ipswich', 'M'),
    ('Jacob Greaves', 'Ipswich', 'D'),
    ('Jacob Ramsey', 'Newcastle', 'M'),
    ('Marcos Senesi', 'Tottenham', 'D'),
    ('Myles Lewis-Skelly', 'Arsenal', 'D,M'),
    ('Robin Roefs', 'Sunderland', 'G'),
    ('Rayan', 'Bournemouth', 'M,F'),
    ('Lucas Gourna-Douath', 'Hull', 'M'),
    ('John McGinn', 'Aston Villa', 'M'),
    ('Noah Okafor', 'Leeds', 'F'),
    ('Malo Gusto', 'Chelsea', 'D,M'),
    ('Joachim Andersen', 'Fulham', 'D'),
    ('Emiliano Buendia', 'Aston Villa', 'M'),
    ('Jack Clarke', 'Ipswich', 'M,F'),
    ('Bart Verbruggen', 'Brighton', 'G'),
    ('Carl Rushworth', 'Coventry', 'G'),
    ('Mateus Fernandes', 'Tottenham', 'M'),
    ('Victor Lindelof', 'Aston Villa', 'D'),
    ('Charalampos Kostoulas', 'Brighton', 'F'),
    ('William Osula', 'Newcastle', 'F'),
    ('Harry Wilson', 'Leeds', 'M,F'),
    ('Jorge Cuenca', 'Fulham', 'D'),
    ('Wilson Isidor', 'Sunderland', 'F'),
    ('Liam Millar', 'Hull', 'M,F'),
    ('Omar Marmoush', 'Tottenham', 'F'),
    ('Loum Tchaouna', 'Coventry', 'M,F'),
    ('Tyrone Mings', 'Aston Villa', 'D'),
    ('Chuba Akpom', 'Ipswich', 'F'),
    ('Georginio Rutter', 'Brighton', 'M,F'),
    ('James Garner', 'Everton', 'D,M'),
    ('Taiwo Awoniyi', 'Coventry', 'F'),
    ('Benjamin Sesko', 'Manchester United', 'F'),
    ('Igor Jesus', 'Nottingham Forest', 'F'),
    ('Tyler Adams', 'Bournemouth', 'M'),
    ('Elliot Stroud', 'Hull', 'M'),
    ('Nico O\'Reilly', 'Manchester City', 'D,M'),
    ('Sander Berge', 'Fulham', 'M'),
    ('Shea Charles', 'Fulham', 'M'),
    ('Ibrahim Sangare', 'Nottingham Forest', 'M'),
    ('Nico Gonzalez', 'Newcastle', 'M'),
    ('Frank Onyeka', 'Coventry', 'M'),
    ('Lisandro Martinez', 'Manchester United', 'D'),
    ('Ben Chilwell', 'Crystal Palace', 'D'),
    ('Jaidon Anthony', 'Brentford', 'M,F'),
    ('Ainsley Maitland-Niles', 'Everton', 'M'),
    ('Brandon Thomas-Asante', 'Coventry', 'F'),
    ('Jeremie Frimpong', 'Liverpool', 'D,M'),
    ('Matt Crooks', 'Hull', 'M'),
    ('Lewis Cook', 'Bournemouth', 'M'),
    ('Ryan Sessegnon', 'Fulham', 'D,M'),
    ('Lukas Nmecha', 'Leeds', 'F'),
    ('Brian Brobbey', 'Sunderland', 'F'),
    ('Ezri Konsa', 'Arsenal', 'D'),
    ('Yasin Ayari', 'Brighton', 'M'),
    ('Mathias Jensen', 'Brentford', 'M'),
    ('Destiny Udogie', 'Tottenham', 'D'),
    ('Archie Gray', 'Tottenham', 'D,M'),
    ('Conor Gallagher', 'Tottenham', 'M'),
    ('Levi Colwill', 'Chelsea', 'D'),
    ('Ethan Pinnock', 'Coventry', 'D'),
    ('Kevin Danso', 'Sunderland', 'D'),
    ('Jorgen Strand Larsen', 'Crystal Palace', 'F'),
    ('Brenden Aaronson', 'Leeds', 'M,F'),
    ('Andrey Santos', 'Manchester United', 'M'),
    ('Nick Woltemade', 'Newcastle', 'M,F'),
    ('Nicolas Jackson', 'Aston Villa', 'F'),
    ('Habib Diarra', 'Sunderland', 'M'),
    ('Robert Sanchez', 'Chelsea', 'G'),
    ('Brennan Johnson', 'Everton', 'M,F'),
    ('Ferdi Kadioglu', 'Brighton', 'D,M'),
    ('Martin Zubimendi', 'Arsenal', 'M'),
    ('Caleb Yirenkyi', 'Coventry', 'M'),
    ('Jannik Schuster', 'Brentford', 'D'),
    ('Gabriel Gudmundsson', 'Leeds', 'D,M'),
    ('Mikey Moore', 'Tottenham', 'F'),
    ('Noussair Mazraoui', 'Manchester United', 'D,M'),
    ('Takehiro Tomiyasu', 'Crystal Palace', 'D'),
    ('Enzo Fernandez', 'Manchester City', 'M'),
    ('Lucas Herrington', 'Hull', 'D'),
    ('Liam Delap', 'Nottingham Forest', 'F'),
    ('Aaron Hickey', 'Brentford', 'D'),
    ('Ayyoub Bouaddi', 'Manchester City', 'M'),
    ('Quinten Timber', 'Crystal Palace', 'M'),
    ('Dwight McNeil', 'Crystal Palace', 'M,F'),
    ('Savio', 'Tottenham', 'M,F'),
    ('Ephron Mason-Clark', 'Coventry', 'M,F'),
    ('Ehor Yarmolyuk', 'Brentford', 'M'),
    ('Costinha', 'Brighton', 'D'),
    ('Cody Drameh', 'Hull', 'D'),
    ('Daniel Munoz', 'Nottingham Forest', 'D,M'),
    ('Hidemasa Morita', 'Hull', 'M'),
    ('Luke O\'Nien', 'Sunderland', 'D,M'),
    ('Ellis Simms', 'Coventry', 'F'),
    ('Pep Chavarria', 'Chelsea', 'D'),
    ('Pau Torres', 'Aston Villa', 'D'),
    ('Rio Ngumoha', 'Liverpool', 'M,F'),
    ('Mohammed Kudus', 'Tottenham', 'M,F'),
    ('Chadi Riad', 'Crystal Palace', 'D'),
    ('Noni Madueke', 'Arsenal', 'M,F'),
    ('Marco Bizot', 'Aston Villa', 'G'),
    ('Jean-Philippe Mateta', 'Crystal Palace', 'F'),
    ('Sean Steur', 'Newcastle', 'M'),
    ('Jack Grealish', 'Everton', 'M'),
    ('Patrick Dorgu', 'Manchester United', 'D,M'),
    ('Matteo Ruggeri', 'Aston Villa', 'D'),
    ('Leny Yoro', 'Manchester United', 'D'),
    ('Ibrahim Osman', 'Brighton', 'F'),
    ('Victor Torp', 'Coventry', 'M'),
    ('Ryan McAidoo', 'Manchester City', 'F'),
    ('Rico Lewis', 'Manchester City', 'D'),
    ('Evann Guessand', 'Crystal Palace', 'M,F'),
    ('Tatsuhiro Sakamoto', 'Coventry', 'M'),
    ('Treymaurice Nyoni', 'Liverpool', 'M'),
    ('Rodrigo Muniz', 'Fulham', 'F'),
    ('Kevin', 'Fulham', 'M,F'),
    ('Mikel Merino', 'Arsenal', 'M,F'),
    ('Ayden Heaven', 'Manchester United', 'D'),
    ('Richarlison', 'Tottenham', 'F'),
    ('Beto', 'Everton', 'F'),
    ('Kasey McAteer', 'Ipswich', 'M'),
    ('Aaron Wan-Bissaka', 'Aston Villa', 'D,M'),
    ('Eberechi Eze', 'Arsenal', 'M,F'),
    ('Romaine Mundle', 'Sunderland', 'M,F'),
    ('Piero Hincapie', 'Arsenal', 'D'),
    ('Alysson', 'Aston Villa', 'F'),
    ('Abdoul Ouattara', 'Ipswich', 'D'),
    ('Gustavo Hamer', 'Coventry', 'M'),
    ('Dominic Solanke', 'Tottenham', 'F'),
    ('Darnell Furlong', 'Ipswich', 'D'),
    ('Sorba Thomas', 'Hull', 'F'),
    ('Bradley Barcola', 'Liverpool', 'F'),
    ('Emile Smith Rowe', 'Fulham', 'M'),
    ('Zian Flemming', 'Ipswich', 'M,F'),
    ('Matheus Nunes', 'Manchester City', 'D,M'),
    ('Oscar Mingueza', 'Crystal Palace', 'D'),
    ('Aladji Bamba', 'Newcastle', 'M'),
    ('Tammy Abraham', 'Aston Villa', 'F'),
    ('Lucas Bergvall', 'Tottenham', 'M'),
    ('James Maddison', 'Tottenham', 'M'),
    ('Zavier Gozo', 'Crystal Palace', 'F'),
    ('Daniel James', 'Leeds', 'M,F'),
    ('Chris Wood', 'Nottingham Forest', 'F'),
    ('Alejandro Garnacho', 'Aston Villa', 'M,F'),
    ('Estevao', 'Chelsea', 'M,F'),
    ('Matias Fernandez-Pardo', 'Newcastle', 'F'),
    ('Alex Toth', 'Bournemouth', 'M'),
    ('Paddy McNair', 'Hull', 'D'),
    ('Ben Doak', 'Bournemouth', 'M,F'),
    ('Callum Wilson', 'Brentford', 'F'),
    ('Hugo Larsson', 'Fulham', 'M'),
    ('Luca Netz', 'Nottingham Forest', 'D'),
    ('Chemsdine Talbi', 'Sunderland', 'M,F'),
    ('Valentin Barco', 'Chelsea', 'D,M'),
    ('Mateo Kovacic', 'Manchester City', 'M'),
    ('Konstantinos Tsimikas', 'Liverpool', 'D'),
    ('Malick Fofana', 'Sunderland', 'F'),
    ('Will Hughes', 'Crystal Palace', 'M'),
    ('Daniel Jebbison', 'Bournemouth', 'F'),
    ('Ryan Christie', 'Bournemouth', 'M'),
    ('Mohamed-Ali Cho', 'Hull', 'F'),
    ('Brooke Norton-Cuffy', 'Hull', 'D'),
    ('Louie Koumas', 'Liverpool', 'F'),
    ('Dario Osorio', 'Crystal Palace', 'M'),
    ('Jacob Murphy', 'Newcastle', 'M,F'),
    ('Zadok Yohanna', 'Brighton', 'F'),
    ('Alvaro Rodriguez', 'Bournemouth', 'F'),
    ('Lamare Bogarde', 'Aston Villa', 'D,M'),
    ('David Brooks', 'Bournemouth', 'M'),
    ('Shea Lacey', 'Manchester United', 'F'),
    ('Geovany Quenda', 'Chelsea', 'M'),
    ('Bruno Guimaraes', 'Arsenal', 'M'),
    ('Chris Rigg', 'Sunderland', 'M'),
    ('Carlos Alcaraz', 'Everton', 'M'),
    ('Matt Targett', 'Hull', 'D'),
    ('Mykhailo Mudryk', 'Tottenham', 'M'),
    ('Moises Caicedo', 'Chelsea', 'M'),
    ('Valentino Livramento', 'Newcastle', 'D'),
    ('Viktor Gyokeres', 'Arsenal', 'F'),
    ('Sindre Egeli', 'Ipswich', 'M,F'),
    ('Sean Longstaff', 'Leeds', 'M'),
    ('Jens Hjerto-Dahl', 'Hull', 'M'),
    ('Joao Gomes', 'Aston Villa', 'M'),
    ('Tim Iroegbunam', 'Hull', 'M'),
    ('Danny Welbeck', 'Chelsea', 'F'),
    ('Rico Henry', 'Brentford', 'D'),
    ('Bazoumana Toure', 'Newcastle', 'F'),
    ('Pascal Struijk', 'Brighton', 'D'),
    ('Ousmane Diomande', 'Nottingham Forest', 'D'),
    ('Callum Hudson-Odoi', 'Nottingham Forest', 'M,F'),
    ('Nicolas Dominguez', 'Nottingham Forest', 'M'),
    ('Vitor Reis', 'Manchester City', 'D'),
    ('Arnaud Kalimuendo', 'Nottingham Forest', 'F'),
    ('Kaden Braithwaite', 'Manchester City', 'D'),
    ('Jeremy Doku', 'Manchester City', 'M,F'),
    ('Jurrien Timber', 'Arsenal', 'D'),
    ('Ismaila Sarr', 'Crystal Palace', 'M,F'),
    ('Amad Diallo', 'Manchester United', 'M,F'),
    ('Johan Manzambi', 'Aston Villa', 'M'),
    ('Kaoru Mitoma', 'Brighton', 'M,F'),
    ('Marco Palestra', 'Chelsea', 'D'),
    ('Yankuba Minteh', 'Brighton', 'M,F'),
    ('William Saliba', 'Arsenal', 'D'),
    ('Ollie Watkins', 'Aston Villa', 'F'),
    ('Eli Kroupi', 'Bournemouth', 'M,F'),
    ('Ibrahim Mbaye', 'Aston Villa', 'F'),
    ('Hugo Ekitike', 'Liverpool', 'F'),
    ('Rayan Ait-Nouri', 'Manchester City', 'D'),
    ('Dejan Kulusevski', 'Tottenham', 'M'),
    ('El Hadji Malick Diouf', 'Brentford', 'D,M'),
    ('Brian Madjo', 'Aston Villa', 'F'),
    ('Haji Wright', 'Coventry', 'F'),
    ('Carlos Baleba', 'Manchester United', 'M'),
    ('Leon Goretzka', 'Aston Villa', 'M'),
    ('Omari Hutchinson', 'Nottingham Forest', 'M,F'),
    ('Gabriel Martinelli', 'Arsenal', 'M,F'),
    ('Nick Pope', 'Newcastle', 'G'),
    ('Sepp van den Berg', 'Brentford', 'D'),
    ('Jaden Philogene', 'Ipswich', 'M,F'),
    ('Dan Burn', 'Newcastle', 'D'),
    ('Joelinton', 'Newcastle', 'M'),
    ('Jake O\'Brien', 'Everton', 'D'),
    ('Christian Norgaard', 'Everton', 'M'),
    ('Max Dowman', 'Arsenal', 'M'),
    ('Allan', 'Manchester City', 'F'),
    ('Kenny Tete', 'Fulham', 'D'),
    ('Xavi Simons', 'Tottenham', 'M,F'),
    ('Michael Keane', 'Everton', 'D'),
    ('Taylor Harwood-Bellis', 'Aston Villa', 'D'),
    ('Matthijs de Ligt', 'Manchester United', 'D'),
    ('Jean-Matteo Bahoya', 'Leeds', 'F'),
    ('Femi Azeez', 'Brighton', 'F'),
    ('Giorgi Mamardashvili', 'Liverpool', 'G'),
    ('Conor Bradley', 'Liverpool', 'D'),
    ('Mason Mount', 'Manchester United', 'M,F'),
    ('Liam Kitching', 'Coventry', 'D'),
    ('Chema Andres', 'Brighton', 'M'),
    ('Ethan Nwaneri', 'Arsenal', 'M'),
    ('Jack Butland', 'Hull', 'G'),
    ('Gabriel Jesus', 'Arsenal', 'F'),
    ('Kepa', 'Arsenal', 'G'),
    ('Juanlu Sanchez', 'Bournemouth', 'M'),
    ('Emmanuel Emegha', 'Chelsea', 'F'),
    ('Tyler Dibling', 'Everton', 'M,F'),
    ('Matt O\'Riley', 'Brighton', 'M'),
    ('Lucas Perri', 'Leeds', 'G'),
    ('Jamie Gittens', 'Chelsea', 'M,F'),
    ('Mike Penders', 'Chelsea', 'G'),
    ('Giovanni Leoni', 'Liverpool', 'D'),
    ('Stefanos Tzimas', 'Brighton', 'F'),
    ('Pape Sarr', 'Tottenham', 'M'),
    ('Joshua Zirkzee', 'Manchester United', 'F'),
    ('Federico Chiesa', 'Liverpool', 'F'),
    ('Amadou Onana', 'Aston Villa', 'M'),
    ('Martin Dubravka', 'Tottenham', 'G'),
    ('Florentino', 'Ipswich', 'M'),
    ('Evan Ferguson', 'Brighton', 'F'),
    ('Amine Adli', 'Bournemouth', 'M,F'),
    ('Wilson Odobert', 'Tottenham', 'M,F'),
    ('Christian Walton', 'Ipswich', 'G'),
    ('Karl Darlow', 'Manchester United', 'G'),
    ('Charlie Hughes', 'Hull', 'D'),
    ('Joe Gelhardt', 'Hull', 'F'),
    ('Jordan Henderson', 'Chelsea', 'M'),
    ('Leon Bailey', 'Aston Villa', 'M,F'),
    ('Bafode Diakite', 'Bournemouth', 'D'),
    ('Harvey Elliott', 'Liverpool', 'M'),
    ('Tosin Adarabioyo', 'Tottenham', 'D'),
    ('George Pickford', 'Everton', 'G'),
    ('Joseph Gomez', 'Liverpool', 'D'),
    ('Simon Adingra', 'Sunderland', 'M,F'),
    ('Jefferson Lerma', 'Crystal Palace', 'D,M'),
    ('Sidiki Cherif', 'Coventry', 'F'),
    ('Dayann Methalie', 'Sunderland', 'D'),
    ('Geronimo Rulli', 'Manchester City', 'G'),
    ('Wilfried Gnonto', 'Leeds', 'F'),
    ('Curtis Jones', 'Liverpool', 'D,M'),
    ('Manuel Ugarte', 'Manchester United', 'M'),
    ('Veljko Milosavljevic', 'Bournemouth', 'D'),
    ('Jason Steele', 'Brighton', 'G'),
    ('Luca Williams-Barnett', 'Tottenham', 'M'),
    ('Harry Amass', 'Manchester United', 'D'),
    ('Illan Meslier', 'Arsenal', 'G'),
    ('Hakon Valdimarsson', 'Brentford', 'G'),
    ('Marc Guiu', 'Chelsea', 'F'),
    ('Antoni Milambo', 'Brentford', 'M'),
    ('Ilyas Ansah', 'Hull', 'F'),
    ('Triston Rowe', 'Aston Villa', 'D'),
    ('Walter Benitez', 'Crystal Palace', 'G'),
    ('Melker Ellborg', 'Sunderland', 'G'),
    ('Reiss Nelson', 'Arsenal', 'F'),
    ('Jeremy Monga', 'Manchester City', 'M,F'),
    ('Fabio Vieira', 'Arsenal', 'M'),
    ('Claudio Echeverri', 'Manchester City', 'M'),
    ('Ben Wilson', 'Coventry', 'G'),
    ('Mark Travers', 'Everton', 'G'),
    ('Benoit Badiashile', 'Chelsea', 'D'),
    ('Romain Esse', 'Crystal Palace', 'M'),
    ('Jonah Kusi-Asare', 'Fulham', 'F'),
    ('Azor Matusiwa', 'Ipswich', 'M'),
    ('Honest Ahanor', 'Crystal Palace', 'D'),
    ('Fabio Carvalho', 'Brentford', 'M'),
    ('Christos Mouzakitis', 'Hull', 'M'),
    ('Jack Taylor', 'Ipswich', 'M'),
    ('Ryan Yates', 'Nottingham Forest', 'M'),
    ('Stefan Bajcetic', 'Liverpool', 'M'),
    ('Dilane Bakwa', 'Nottingham Forest', 'M,F'),
    ('Kaye Furo', 'Brentford', 'F'),
    ('Julian Araujo', 'Bournemouth', 'D'),
    ('John Victor', 'Nottingham Forest', 'G'),
    ('Ben Davies', 'Tottenham', 'D'),
    ('Tyler Fletcher', 'Manchester United', 'M'),
    ('Mamadou Sarr', 'Chelsea', 'D'),
    ('Tom Cairney', 'Fulham', 'M'),
    ('Dario Essugo', 'Chelsea', 'M'),
    ('Modou Cisse', 'Aston Villa', 'D,M'),
    ('Justin Devenny', 'Crystal Palace', 'M,F'),
    ('Tom Heaton', 'Manchester United', 'G'),
    ('Adam Aznou', 'Everton', 'D'),
    ('Fraser Forster', 'Bournemouth', 'G'),
    ('Ewen Jaouen', 'Newcastle', 'G'),
    ('Marcus Bettinelli', 'Manchester City', 'G'),
    ('Freddie Woodman', 'Liverpool', 'G'),
    ('Cheick Doucoure', 'Crystal Palace', 'M'),
    ('Oliver Dovin', 'Coventry', 'G'),
    ('Wataru Endo', 'Liverpool', 'M'),
    ('Matheus Franca', 'Crystal Palace', 'F'),
    ('Morato', 'Nottingham Forest', 'D'),
    ('Nicolo Savona', 'Nottingham Forest', 'D'),
    ('Michael Svoboda', 'Brighton', 'D'),
    ('Igor Julio', 'Brighton', 'D'),
    ('Zach Abbott', 'Nottingham Forest', 'D'),
    ('Jack Fletcher', 'Manchester United', 'M'),
    ('Ilia Gruev', 'Leeds', 'M'),
    ('Robinio Vaz', 'Hull', 'F'),
    ('Reggie Watson', 'Chelsea', 'M'),
    ('Michele Di Gregorio', 'Bournemouth', 'G'),
    ('Jaouen Hadjam', 'Brighton', 'D'),
    ('Sean Neave', 'Newcastle', 'F'),
    ('Mahdi Nicoll-Jazuli', 'Chelsea', 'M'),
    ('Gustavo Nunes', 'Brentford', 'F'),
    ('Nathan Patterson', 'Everton', 'D'),
    ('Borna Sosa', 'Crystal Palace', 'D'),
    ('Souza', 'Tottenham', 'D'),
    ('Ajibola Alese', 'Sunderland', 'D'),
    ('Aaron Anselmino', 'Chelsea', 'D'),
    ('Kim Ji-Soo', 'Brentford', 'D'),
    ('Simon Moore', 'Sunderland', 'G'),
    ('Ifeanyi Ndukwe', 'Liverpool', 'D'),
    ('David Ozoh', 'Crystal Palace', 'M'),
    ('James Scanlon', 'Arsenal', 'M'),
    ('Gabriel Slonina', 'Chelsea', 'G'),
    ('Olutayo Subuloye', 'Chelsea', 'D'),
    ('Josh Eccles', 'Coventry', 'M'),
    ('Julio Soler', 'Bournemouth', 'D'),
    ('Steven Benda', 'Nottingham Forest', 'G'),
    ('Alan Browne', 'Sunderland', 'M'),
    ('Bradley Burrowes', 'Aston Villa', 'M,F'),
    ('Sam Byram', 'Leeds', 'D'),
    ('Toby Collyer', 'Manchester United', 'M'),
    ('Luc De Fougerolles', 'Fulham', 'D'),
    ('Mikel Jack', 'Tottenham', 'G'),
    ('Benjamin Lecomte', 'Fulham', 'G'),
    ('Remi Matthews', 'Crystal Palace', 'G'),
    ('Habeeb Ogunneye', 'Arsenal', 'D'),
    ('Alex Palmer', 'Ipswich', 'G'),
    ('Jesurun Rak-Sakyi', 'Crystal Palace', 'M,F'),
    ('David Affengruber', 'Fulham', 'D'),
    ('Matai Akinmboni', 'Bournemouth', 'D'),
    ('Luka Lynch', 'Aston Villa', 'F'),
    ('Anis Mehmeti', 'Ipswich', 'M'),
    ('Manuel Angel', 'Fulham', 'M'),
    ('Harrison Reed', 'Fulham', 'M'),
    ('Jenson Seelt', 'Sunderland', 'D'),
    ('Max Aarons', 'Bournemouth', 'D'),
    ('Jules Ahoka', 'Sunderland', 'M'),
    ('Brandon Austin', 'Tottenham', 'G'),
    ('Tyler Bindon', 'Nottingham Forest', 'D'),
    ('David Button', 'Ipswich', 'G'),
    ('Max-Edgar Chabot', 'Manchester City', 'G'),
    ('Rhys Chadwick', 'Leeds', 'M'),
    ('Amario Cozier-Duberry', 'Brighton', 'M'),
    ('Braiden Graham', 'Everton', 'F'),
    ('Darko Gyabi', 'Hull', 'M'),
    ('Vitezslav Jaros', 'Liverpool', 'G'),
    ('Cedric Kipre', 'Ipswich', 'D'),
    ('Stephen Mfuni', 'Coventry', 'D'),
    ('Chiedozie Ogbene', 'Ipswich', 'F'),
    ('Dillon Phillips', 'Hull', 'G'),
    ('Calvin Ramsay', 'Liverpool', 'D'),
    ('Remy Rees-Dottin', 'Bournemouth', 'F'),
    ('Joshua Wilson-Esbrand', 'Manchester City', 'D'),
    ('Miracle Adewole', 'Tottenham', 'D'),
    ('Ellery Balcombe', 'Brentford', 'G'),
    ('Jocelin Ta Bi', 'Sunderland', 'M,F'),
    ('Raphael Borges Rodrigues', 'Coventry', 'F'),
    ('Eiran Cashin', 'Brighton', 'D'),
    ('Kieran Dowell', 'Hull', 'M'),
    ('Mark Gillespie', 'Newcastle', 'G'),
    ('Kaine Hayden', 'Coventry', 'D'),
    ('Rory Mahady', 'Leeds', 'G'),
    ('Jayden Meghoma', 'Brentford', 'D'),
    ('Lucas Pitt', 'Liverpool', 'D'),
    ('Omar Richards', 'Nottingham Forest', 'D'),
    ('Dane Scarlett', 'Tottenham', 'F'),
    ('Kota Takai', 'Tottenham', 'D'),
    ('David Akintola', 'Hull', 'M,F'),
    ('Owen Asemota', 'Aston Villa', 'G'),
    ('Daniel Bentley', 'Coventry', 'G'),
    ('Lucca Brughmans', 'Liverpool', 'G'),
    ('Alex Cairns', 'Leeds', 'G'),
    ('Alfie Cresswell', 'Leeds', 'M'),
    ('William Dennis', 'Bournemouth', 'G'),
    ('Aidan Harris', 'Newcastle', 'G'),
    ('Solomon Honor', 'Manchester United', 'G'),
    ('Tom King', 'Everton', 'G'),
    ('Theo Mawene', 'Brentford', 'F'),
    ('James McConnell', 'Liverpool', 'M'),
    ('Dermot Mee', 'Manchester United', 'G'),
    ('Callum Mills', 'Leeds', 'M'),
    ('Nehemiah Oriola', 'Brighton', 'F'),
    ('Leo Shahar', 'Newcastle', 'D'),
    ('Oscar Zambrano', 'Hull', 'M'),
    ('Kayne van Oevelen', 'Ipswich', 'G'),
    ('Juan Angulo', 'Sunderland', 'F'),
    ('Abdoullah Ba', 'Sunderland', 'M'),
    ('Melvin Bard', 'Leeds', 'D'),
    ('Jake Bidwell', 'Coventry', 'D'),
    ('Alex Borto', 'Fulham', 'G'),
    ('Sam Chambers', 'Leeds', 'M'),
    ('Reiss Elliot-Parris', 'Tottenham', 'F'),
    ('Jayden Lienou', 'Leeds', 'D'),
    ('Matias Orozco', 'Brighton', 'M'),
    ('Floyd Samba', 'Manchester City', 'M'),
    ('Joseph Whitworth', 'Crystal Palace', 'G'),
    ('Luke Woolfenden', 'Coventry', 'D'),
    ('Macauley Zepa', 'Fulham', 'F'),
    ('Eric da Silva Moreira', 'Nottingham Forest', 'F'),
    ('Michael Zetterer', 'Leeds', 'G'),
    ('Miguel Angel Brau', 'Coventry', 'D'),
    ('Josh Dasilva', 'Brentford', 'M'),
    ('Harvey Davies', 'Liverpool', 'G'),
    ('Harvey Foster', 'Everton', 'M'),
    ('Fred Heath', 'Manchester United', 'G'),
    ('Henry Johnson', 'Newcastle', 'D'),
    ('Joel Latibeaudiere', 'Coventry', 'D'),
    ('Thomas McGill', 'Brighton', 'G'),
    ('Natalia Ramos', 'Liverpool', 'D'),
    ('Tommy Setford', 'Arsenal', 'G'),
    ('Luis Semedo', 'Sunderland', 'F'),
    ('Charlie Tasker', 'Brighton', 'D'),
    ('James Wright', 'Aston Villa', 'G'),
    ('Keith Andrews', 'Coventry', 'M'),
    ('Caelan Avenell', 'Brentford', 'D'),
    ('Benjamin Fredrick', 'Brentford', 'D'),
    ('Archie Howard', 'Hull', 'G'),
    ('Matty Jacob', 'Hull', 'D'),
    ('Eliot Matazo', 'Hull', 'M'),
    ('Jesse Middleton', 'Brighton', 'M'),
    ('Luca Picotto', 'Brentford', 'M'),
    ('Teddy Sharman-Lowe', 'Chelsea', 'G'),
    ('Abdulkadir Omur', 'Hull', 'M'),
    ('Charlie Compton', 'Ipswich', 'M'),
    ('Yann Gboho', 'Coventry', 'F'),
    ('Andre Grey', 'Brentford', 'M'),
    ('Shane Nti', 'Brighton', 'M'),
    ('Chibby Nwoko', 'Fulham', 'M'),
    ('Jorja Fox', 'Ipswich', 'D'),
    ('Cameron Humphreys', 'Ipswich', 'M'),
    ('Tudor Mendel-Idowu', 'Ipswich', 'M'),
    ('Darryl Ombang', 'Leeds', 'G'),
    ('Josh Robertson', 'Brighton', 'M'),
    ('Tyrell Sellars-Fleming', 'Hull', 'F'),
    ('Freddie Simmonds', 'Brighton', 'D'),
    ('Bradley Slade', 'Fulham', 'D'),
    ('Omar Alderete', 'Sunderland', 'D'),
    ('Fabian Schar', 'Newcastle', 'D'),
    ('Promise David', 'Brighton', 'F'),]


def normalize(name):
    decomposed = unicodedata.normalize('NFKD', name)
    return ''.join(c for c in decomposed if not unicodedata.combining(c)).lower().strip()


def main():
    fantrax_by_norm = {}
    for name, club, pos in FANTRAX_ROWS:
        fantrax_by_norm.setdefault(normalize(name), []).append((name, club, pos))
    current_pl_clubs = {c for _, c, _ in FANTRAX_ROWS}

    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    players = conn.execute("SELECT name, club, position FROM players WHERE draftable=1").fetchall()

    exact_mismatches = []
    fuzzy_mismatches = []
    no_match = []

    for p in players:
        if p['club'] not in current_pl_clubs:
            continue  # not on a current top-flight club on our side either -- out of scope
        n = normalize(p['name'])
        if n in fantrax_by_norm:
            candidates = fantrax_by_norm[n]
            if not any(c[1] == p['club'] for c in candidates):
                exact_mismatches.append((p['name'], p['club'], p['position'], candidates))
            continue
        close = difflib.get_close_matches(n, fantrax_by_norm.keys(), n=3, cutoff=0.82)
        if close:
            candidates = [c for k in close for c in fantrax_by_norm[k]]
            if not any(c[1] == p['club'] for c in candidates):
                fuzzy_mismatches.append((p['name'], p['club'], p['position'], candidates))
        else:
            no_match.append((p['name'], p['club'], p['position']))

    print(f"Checked {len(players)} draftable players on a current-season club.\n")

    print(f"=== {len(exact_mismatches)} EXACT name match, club differs (high confidence) ===")
    for name, club, pos, candidates in exact_mismatches:
        fantrax_clubs = ', '.join(f"{c[1]!r}" for c in candidates)
        print(f"  {name} ({pos}): on file as {club!r}, Fantrax says {fantrax_clubs}")
    print()

    print(f"=== {len(fuzzy_mismatches)} FUZZY name match, club differs (verify before acting) ===")
    for name, club, pos, candidates in fuzzy_mismatches:
        print(f"  {name} ({pos}) on file as {club!r} -- closest Fantrax candidate(s):")
        for c in candidates:
            print(f"      {c[0]!r} ({c[2]}) -- {c[1]!r}")
    print()

    print(f"=== {len(no_match)} player(s) with no Fantrax match at all (usually fine -- see note above) ===")
    for name, club, pos in no_match:
        print(f"  {name} ({pos}, {club})")

    conn.close()


if __name__ == '__main__':
    main()
